version: '3.2'
services:
  mongo:
    image: mongo
    command: mongod --dbpath /data/db --auth
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./db:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  python:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mongo
    network_mode: "host"
